In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_excel("quickcart_ecommerce_orders_1200_rows.xlsx")
df.head()

,Order_ID,Order_Date,Order_Time,City,Warehouse_ID,Product_ID,Product_Category,Product_Name,Price,Quantity,Stock_Available,Delivery_Partner,Delivery_Time_Minutes,Customer_Rating,Payment_Method
0,QC1000,2025-04-08,16:47,Chennai,W3,P190,Bakery,Bread,79,5,26,Ravi,25,3.1,UPI
1,QC1001,2025-02-18,18:52,Mumbai,W2,P884,Frozen,Ice Cream,193,2,20,Karthik,20,3.1,COD
2,QC1002,2025-03-19,21:43,Chennai,W2,P500,Dairy,Milk 1L,118,4,33,Vikram,27,3.3,UPI
3,QC1003,2025-03-14,09:24,Bangalore,W6,P796,Bakery,Cake,61,5,37,Aman,15,3.6,UPI
4,QC1004,2025-04-21,08:56,Pune,W4,P138,Beverages,Energy Drink,41,5,46,Rahul,48,3.7,Card

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               1200 non-null   str
 1   Order_Date             1200 non-null   str
 2   Order_Time             1200 non-null   str
 3   City                   1200 non-null   str
 4   Warehouse_ID           1200 non-null   str
 5   Product_ID             1200 non-null   str
 6   Product_Category       1200 non-null   str
 7   Product_Name           1200 non-null   str
 8   Price                  1200 non-null   int64
 9   Quantity               1200 non-null   int64
 10  Stock_Available        1200 non-null   int64
 11  Delivery_Partner       1200 non-null   str
 12  Delivery_Time_Minutes  1200 non-null   int64
 13  Customer_Rating        1200 non-null   float64
 14  Payment_Method         1200 non-null   str
dtypes: float64(1), int64(4), str(10)
memory usage: 140.8 KB

In [27]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'City', 'Warehouse_ID',
       'Product_ID', 'Product_Category', 'Product_Name', 'Price', 'Quantity',
       'Stock_Available', 'Delivery_Partner', 'Delivery_Time_Minutes',
       'Customer_Rating', 'Payment_Method'],
      dtype='str')

In [28]:
df.describe()

,Price,Quantity,Stock_Available,Delivery_Time_Minutes,Customer_Rating
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,142.591667,2.941667,29.482500,30.193333,3.973333
std,62.340920,1.414189,17.951088,11.737863,0.574004
min,30.000000,1.000000,0.000000,10.000000,3.000000
25%,92.000000,2.000000,14.000000,20.000000,3.500000
50%,146.000000,3.000000,29.000000,30.000000,4.000000
75%,193.000000,4.000000,45.000000,40.000000,4.500000
max,250.000000,5.000000,60.000000,50.000000,5.000000

In [29]:
df.isnull().sum()

Order_ID                 0
Order_Date               0
Order_Time               0
City                     0
Warehouse_ID             0
Product_ID               0
Product_Category         0
Product_Name             0
Price                    0
Quantity                 0
Stock_Available          0
Delivery_Partner         0
Delivery_Time_Minutes    0
Customer_Rating          0
Payment_Method           0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [32]:
df["City"] = df["City"].str.strip()
df["Product_Category"] = df["Product_Category"].str.title()
df["Payment_Method"] = df["Payment_Method"].str.upper()

In [33]:
df["Revenue"] = df["Price"] * df["Quantity"]

In [34]:
df["Month"] = df["Order_Date"].dt.month_name()
df["Day"] = df["Order_Date"].dt.day_name()

In [36]:
df["Order_Year"] = df["Order_Date"].dt.year
df["Order_Month"] = df["Order_Date"].dt.month

In [23]:
df["City"].unique()

df["Payment_Method"].unique()

df["Product_Category"].unique()

<StringArray>
['Bakery', 'Frozen', 'Dairy', 'Beverages', 'Fruits', 'Snacks']
Length: 6, dtype: str

In [37]:
df["Delivery_Speed"] = np.where(
df["Delivery_Time_Minutes"] < 30,
"Fast",
np.where(
df["Delivery_Time_Minutes"] < 60,
"Medium",
"Slow"
)
)

In [38]:
df["Stock_Status"] = np.where(
df["Stock_Available"] < 20,
"Low Stock",
"In Stock"
)

In [39]:
df.to_csv("quickcart_cleaned_orders.csv", index=False)

In [40]:
import pandas as pd
from sqlalchemy import create_engine

In [41]:
df = pd.read_csv("quickcart_cleaned_orders.csv")

df.head()

,Order_ID,Order_Date,Order_Time,City,Warehouse_ID,Product_ID,Product_Category,Product_Name,Price,Quantity,...,Delivery_Time_Minutes,Customer_Rating,Payment_Method,Revenue,Month,Day,Order_Year,Order_Month,Delivery_Speed,Stock_Status
0,QC1000,2025-04-08,16:47,Chennai,W3,P190,Bakery,Bread,79,5,...,25,3.1,UPI,395,April,Tuesday,2025,4,Fast,In Stock
1,QC1001,2025-02-18,18:52,Mumbai,W2,P884,Frozen,Ice Cream,193,2,...,20,3.1,COD,386,February,Tuesday,2025,2,Fast,In Stock
2,QC1002,2025-03-19,21:43,Chennai,W2,P500,Dairy,Milk 1L,118,4,...,27,3.3,UPI,472,March,Wednesday,2025,3,Fast,In Stock
3,QC1003,2025-03-14,09:24,Bangalore,W6,P796,Bakery,Cake,61,5,...,15,3.6,UPI,305,March,Friday,2025,3,Fast,In Stock
4,QC1004,2025-04-21,08:56,Pune,W4,P138,Beverages,Energy Drink,41,5,...,48,3.7,CARD,205,April,Monday,2025,4,Medium,In Stock

In [42]:
engine = create_engine("mysql+pymysql://root:12345@localhost:3306/quickcart_db")

In [44]:
df.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

1200